Pfs 78 invoice gen billing event
ministryofjustice/opg-sirius-supervision-finance-hub pull request #100
Opened 2024-07-11 10:39 UTC by Nicholassully

2024-07-12 09:27 UTC, denialanderror requested changes

2024-07-12 09:27 UTC, denialanderror commented on finance-api/internal/service/billing_history.go
> +	history = processAllocations(allocationsByLedger, history)
Why do you pass history into this function when it is only used for appending the allocations? If that's all it is being used for, you can just do `history = append(history, processAllocations(allocationsByLedger)...)`

2024-07-12 09:36 UTC, Nicholassully commented on finance-api/internal/service/billing_history.go
> +	balanceAdjustment float64
It was not showing decimal places in the front

2024-07-12 09:37 UTC, Nicholassully commented on shared/billing_history.go
> +	OutstandingBalance float64      `json:"outstanding_balance"`
It was not showing decimal places in the front

2024-07-12 09:39 UTC, Nicholassully commented on finance-api/internal/store/queries/billing_history.sql
> +SELECT i.id invoice_id, reference, feetype, amount, createdby_id, coalesce(confirmeddate, createddate) invoice_date
I thought that the timeline needed to show when things were made or changed. If we use raiseddate they could put any date into that and it would not show correctly in the time line

2024-07-12 09:40 UTC, Nicholassully commented on finance-api/internal/service/billing_history.go
> +		outstanding += bh.balanceAdjustment
This was not needed any more I thought before it was. Checking and seeing the tests it was logic that just bloated the code

2024-07-12 09:47 UTC, Nicholassully commented on finance-api/internal/service/billing_history.go
> +func processAllocations(allocationsByLedger map[int32]allocationHolder, holder []historyHolder) []historyHolder {
done

2024-07-12 09:53 UTC, Nicholassully commented on finance-api/internal/service/billing_history.go
> +	history = processAllocations(allocationsByLedger, history)
good point done

2024-07-12 10:16 UTC, denialanderror commented on finance-api/internal/service/billing_history.go
> +	balanceAdjustment float64
Well yes, it wouldn't. this isn't where you should be converting it to anything though. The API should return data in its most applicable state. The consumer of that API (the FE in this case) can do whatever it wants to with that data in order to display it or perform additional calculations on it.

2024-07-12 10:17 UTC, denialanderror commented on shared/billing_history.go
> +	Amount           string       `json:"amount"`
See other comment

2024-07-12 10:17 UTC, denialanderror commented on finance-api/internal/store/queries/billing_history.sql
> +SELECT i.id invoice_id, reference, feetype, amount, createdby_id, coalesce(confirmeddate, createddate) invoice_date
Check with Alex. That's what it says to use on the ticket.

2024-07-12 10:20 UTC, denialanderror commented on shared/billing_history.go
> +	OutstandingBalance float64      `json:"outstanding_balance"`
See other comment

2024-07-12 10:41 UTC, denialanderror commented on finance-api/internal/service/billing_history.go
> +		outstanding += bh.balanceAdjustment
Okay that's fine. It will just need to be all added back in again when the approved adjustments and payments events are added.

2024-07-12 10:42 UTC, Nicholassully commented on finance-api/internal/store/queries/billing_history.sql
> +SELECT i.id invoice_id, reference, feetype, amount, createdby_id, coalesce(confirmeddate, createddate) invoice_date
Alex Holmes
:spiral_calendar_pad:  [11:41 AM](https://mojdt.slack.com/archives/D01D43M6X6V/p1720780905110749)
Created date should be the preferred order yeah!

2024-07-15 09:20 UTC, denialanderror submitted a review, later dismissed

2024-07-15 13:05 UTC, Nicholassully commented on finance-hub/internal/server/billing_history.go
> +func (h *BillingHistoryHandler) DivideByHundred(value int) float64 {
removed

2024-07-15 13:05 UTC, Nicholassully commented on shared/billing_history.go
> +func (b *BillingHistory) IntToDecimal(amount int) string {
done

2024-07-18 08:39 UTC, josephsmith0705 approved these changes

2024-07-18 08:40 UTC, denialanderror approved these changes

2024-07-18 08:45 UTC, merged