PFS-37 write off reversal invoice adjustment
ministryofjustice/opg-sirius-supervision-finance-hub pull request #132
Opened 2024-09-02 14:22 UTC by josephsmith0705

2024-09-18 06:59 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +		if il.Type == "WRITE OFF REVERSAL" {
Is there a test for this, also how come we are not checking this before the other `if` conditions as we change the value after

2024-09-18 07:19 UTC, denialanderror requested changes

2024-09-18 07:19 UTC, denialanderror commented on cypress/e2e/customer-credit-balance.cy.js
> +        const amounts = ["£30", "£30", "£100"];
Why has the minus been removed from the unapplied amount?

2024-09-18 07:19 UTC, denialanderror commented on finance-api/internal/service/add_invoice_adjustment.go
> +			if balance.Initial > customerCreditBalance {
Not sure this is correct. A write off is calculated as the outstanding balance, not the initial amount. e.g. an invoice of £100 that has a partial payment of £20 would have a write off of £80.

2024-09-18 07:19 UTC, denialanderror commented on finance-api/internal/service/invoice_adjustments.go
> +			Amount:         int(math.Abs(float64(ia.Amount))),
Same question as above re: this no longer being negative.

If this change is a requirement, this wouldn't be the right place to call abs. The API should return the data in as true a representation as possible. If the UI wants to display all values as positive, it should do that transformation itself.

2024-09-18 08:07 UTC, josephsmith0705 commented on finance-api/internal/service/invoice_adjustments.go
> +			Amount:         int(math.Abs(float64(ia.Amount))),
This was a request from Alex, that the transaction type should indicate to the users whether it'll be positive or negative, so the minus is not needed - I'll move it to the frontend, rather than the api

2024-09-18 10:31 UTC, josephsmith0705 commented on finance-api/internal/service/invoices.go
> +		if il.Type == "WRITE OFF REVERSAL" {
Good spot, I've added a test and moved it up above the other conditions

2024-09-18 12:59 UTC, denialanderror commented on finance-api/internal/service/invoice_adjustments.go
> +			Amount:         int(math.Abs(float64(ia.Amount))),
Oh okay. That's a bit weird, seeing as we have tickets in the backlog for moving the minus from "£-" to "-£".

2024-09-18 13:15 UTC, denialanderror commented on finance-api/internal/service/add_invoice_adjustment.go
> +	writeOffAmount, err := s.store.GetMostRecentApprovedWriteOffAmount(ctx, int32(invoiceId))
I'd be tempted to include the write off amount in `GetInvoiceBalanceDetails` instead of another query. It already fetches a boolean for if it the invoice has been written off so you could just change that to an int and use zero of the false value.

2024-09-23 08:52 UTC, denialanderror commented on finance-hub/internal/util/translate.go
> +		"thousand-character-limit": pair{"Notes", "Reason for adjustment must be 1000 characters or less"},
There appears to be two validation messages for the same error

2024-09-23 09:37 UTC, denialanderror approved these changes

2024-09-23 09:37 UTC, merged