pfs-19 and pfs-27 invoice with drop down frontend done #minor
ministryofjustice/opg-sirius-supervision-finance-hub pull request #14
Opened 2024-02-23 10:57 UTC by Nicholassully

2024-02-23 11:59 UTC, denialanderror requested changes

2024-02-23 11:59 UTC, denialanderror commented on cypress/e2e/invoices.cy.js
> +    describe("Invoices ledger allocations", () => {
These tests are just testing the headers, not the actual data. It's also just checking those elements are on the page, not that they are in the right locations.

2024-02-23 11:59 UTC, denialanderror commented on internal/model/invoices.go
> +	Invoices []Invoice `json:"invoices"`
The API would probably be cleaner if /invoices returned an array of invoices rather than an object with an invoices array field.

2024-02-23 11:59 UTC, denialanderror commented on internal/model/invoices.go
> +	Received           string             `json:"received"`
These should probably be dates. We want our API to be agnostic of how the data is being used, so having these dates as preformatted date strings would be an anti-pattern

2024-02-23 11:59 UTC, denialanderror commented on internal/sirius/get_invoices.go
> +	//see returning just one odject not an array
Not sure I understand this comment or what the above iteration is doing. `invoiceList.Invoices` is an array of invoices, and you are iterating through the array, copying the elements, and reassigning the same data back to the invoices list.

2024-02-23 11:59 UTC, denialanderror commented on web/assets/main.js
> +function toggleSummary(summeryId) {
summary not "summery"

2024-02-23 11:59 UTC, denialanderror commented on web/assets/main.js
> +        let summeryId = summary.id
Use const over let unless you need it to be mutable

2024-02-23 11:59 UTC, denialanderror commented on web/template/tabs/invoices-list.gotmpl
> +{{/*        <tr class="govuk-table__row">*/}}
Comments?

2024-02-23 11:59 UTC, denialanderror commented on web/template/tabs/invoices-list.gotmpl
There's a lot of inline styles here. These should all be css classes

2024-02-23 11:59 UTC, denialanderror commented on internal/server/invoices_test.go
No test for the success path

2024-02-26 09:15 UTC, Nicholassully commented on internal/model/invoices.go
> +	Invoices []Invoice `json:"invoices"`
done

2024-02-26 09:15 UTC, Nicholassully commented on internal/model/invoices.go
> +	Received           string             `json:"received"`
done

2024-02-26 09:15 UTC, Nicholassully commented on internal/sirius/get_invoices.go
> +	//see returning just one odject not an array
done

2024-02-26 09:15 UTC, Nicholassully commented on web/assets/main.js
> +function toggleSummary(summeryId) {
done

2024-02-26 09:15 UTC, Nicholassully commented on web/assets/main.js
> +        let summeryId = summary.id
done

2024-02-26 09:15 UTC, Nicholassully commented on web/template/tabs/invoices-list.gotmpl
> +{{/*        <tr class="govuk-table__row">*/}}
done

2024-02-26 09:15 UTC, Nicholassully commented on web/template/tabs/invoices-list.gotmpl
done

2024-02-26 09:15 UTC, Nicholassully commented on internal/server/invoices_test.go
done

2024-02-26 10:01 UTC, Nicholassully commented on cypress/e2e/invoices.cy.js
> +    describe("Invoices ledger allocations", () => {
I was thinking that in the cypress test I would only test the headers as they are static and unit test would look more into the data?

2024-03-14 06:38 UTC, closed without merging