PFS-130 Process moto card payments upload
ministryofjustice/opg-sirius-supervision-finance-hub pull request #149
Opened 2024-09-30 14:27 UTC by josephsmith0705

2024-10-10 15:42 UTC, denialanderror requested changes
I'd rename references to CaseRecNumber number to "CourtRef". Casrec was the old system in place before Sirius, so it would be good to move away from that where possible.

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/awsclient/client.go
> +package awsclient
`awsclient` implies this is the client for all AWS integration, but we use a different client for EventBridge. I'd suggest renaming it. `filestorage`? `storage`?

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/finance_clients.go
> +	if err != nil {
Instead of this conditional, you can just `return err`, as if it is nil, you return it later anyway.

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +	client, _ := awsclient.NewClient(ctx)
Clients are typically designed to be created once at start up and then reused, rather than initialised on each function call. You can add it to the Service struct in the same way I did with the EventBridge client.

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +	output, err := client.GetObject(ctx, &s3.GetObjectInput{
It would be nice to avoid leaking AWS implementation into the service, e.g. if the call on the client just took a key and bucket name as strings and handled the types and parameter parsing internally.

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +func (s *Service) processMotoCardPaymentsUploadLine(ctx context.Context, record []string) error {
This will all need wrapping in a transaction. Otherwise, if it failed halfway through, it could create a ledger in the DB but not associate it with any payments.

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +		if !(invoice.Amount == invoice.Received) && amount > 0 {
If you filter out the closed/paid invoices in the query (e.g. with a HAVING clause), you won't need this check

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +		Status:        "APPROVED",
We will be getting rid of ledger status eventually but I think the correct status her to keep in line with existing payments is "CONFIRMED"

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +func parseAmount(amount string) int {
If you return int32 here, you won't have to do so much type conversion in the process function

2024-10-10 15:42 UTC, denialanderror commented on finance-api/internal/store/queries/invoices.sql
> +       COALESCE(MAX(fr.type), '')::VARCHAR fee_reduction_type
Is fee reduction used in processing this file?

2024-10-10 15:42 UTC, denialanderror commented on migrations/20241002141959_finance_client_caserecnumber.sql
> +ALTER TABLE finance_client ADD COLUMN caserecnumber varchar(255);
You may want to add an index along with this if that's how we are querying by

2024-10-21 11:34 UTC, josephsmith0705 commented on finance-api/internal/store/queries/invoices.sql
> +       COALESCE(MAX(fr.type), '')::VARCHAR fee_reduction_type
You're right, it's not - there were a bunch of unused returns here that I've reduced to only what is needed

2024-10-21 13:51 UTC, denialanderror approved these changes
Re: transactions, we should probably do some performance testing at some point. This approach means that if one line fails, the previous successful ones aren't rolled back, which is good, but it also means we are doing a database hit for each line. We could instead batch the changes and commit e.g. every 50 rows if performance is being impacted.

2024-10-21 15:14 UTC, merged