PFS-132 Upload supervision BACS payments file
ministryofjustice/opg-sirius-supervision-finance-hub pull request #158
Opened 2024-10-28 20:19 UTC by josephsmith0705

2024-11-11 14:20 UTC, jackgoodby submitted a review, later dismissed

2024-11-11 15:38 UTC, denialanderror requested changes

2024-11-11 15:38 UTC, denialanderror commented on finance-api/internal/service/process_finance_admin_upload.go
> +		uploadProcessedEvent.Error = "Unable to download report"
Can you include the report filename in these errors? Or, seeing as this is being returned as part of the upload event, include the name in that?

2024-11-12 13:20 UTC, denialanderror approved these changes

2024-11-12 13:25 UTC, merged