Pfs 3 header and footer
ministryofjustice/opg-sirius-supervision-finance-hub pull request #2
Opened 2024-01-24 10:49 UTC by Nicholassully

2024-01-24 11:47 UTC, denialanderror requested changes

2024-01-24 11:47 UTC, denialanderror commented on internal/model/assignee.go
> +}
Do we need all this assignee information? We should only be adding to the struct the data we need, otherwise it all bloats unnecessarily.

2024-01-24 11:47 UTC, denialanderror commented on internal/server/environment_vars.go
> +		SiriusURL:       getEnv("SIRIUS_URL", "http://host.docker.internal:8080"),
It would be better to pass this through in a compose file, rather than default it here

2024-01-24 11:47 UTC, denialanderror commented on web/template/inserts/header.gotmpl
> +  <sirius-header {{ if eq .Error "" }} {{ end }}></sirius-header>
What's the point of this if condition?

2024-01-25 13:01 UTC, Nicholassully commented on internal/model/assignee.go
> +}
done

2024-01-25 13:03 UTC, Nicholassully commented on internal/server/environment_vars.go
> +		SiriusURL:       getEnv("SIRIUS_URL", "http://host.docker.internal:8080"),
done

2024-01-25 13:03 UTC, Nicholassully commented on web/template/inserts/header.gotmpl
> +  <sirius-header {{ if eq .Error "" }} {{ end }}></sirius-header>
done

2024-01-26 10:22 UTC, denialanderror reviewed
Why are user details being fetched in this PR if they are never being used?

2024-01-26 10:35 UTC, Nicholassully commented
They dont need to fetch in this one but they are need in pfs-5 so should of been done in that one. For now is it ok if they go in as I will need them for the next ticket I am doing?

2024-01-30 14:52 UTC, denialanderror approved these changes

2024-01-30 15:10 UTC, merged