Pfs 50 invoices backend
ministryofjustice/opg-sirius-supervision-finance-hub pull request #27
Opened 2024-03-27 15:06 UTC by Nicholassully

2024-04-02 08:33 UTC, josephsmith0705 commented on cypress/e2e/invoices.cy.js
> +// });
Will we be able to uncomment these for some future work? Or, can we remove these commented lines

2024-04-02 08:35 UTC, josephsmith0705 submitted a review, later dismissed

2024-04-03 06:29 UTC, Nicholassully commented on cypress/e2e/invoices.cy.js
> +// });
Yes in the next ticket this test will be needed

2024-04-03 09:39 UTC, denialanderror requested changes

2024-04-03 09:39 UTC, denialanderror commented on cypress/e2e/invoices.cy.js
> +// });
Could you stick a TODO comment with the ticket number it is meant to be done on, so if it gets missed we know when it should have been?

2024-04-04 07:23 UTC, Nicholassully commented on cypress/e2e/invoices.cy.js
> +// });
done

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/cmd/api/invoices.go
> +	if err != nil {
done

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +func (s *Service) GetInvoices(id int) (*shared.Invoices, error) {
done

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +	}
done

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +	fc, err := s.Store.GetInvoices(ctx, pgtype.Int4{Int32: int32(id), Valid: true})
Yeah I was trying not to do anything like what I did but the sql thats generated makes the data type pgtype.Int4 so I do need to change the type in less there is a better way

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +			TransactionType: "unknown",
Something we need to go through together on this one

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +			ReceivedDate:    shared.Date{Time: i.Allocateddate.Time},
Then we cant use the shared struct I thought?

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/store/queries/finance_client.sql
> +SELECT cacheddebtamount, cachedcreditamount, payment_method FROM finance_client WHERE client_id = $1;
done

2024-04-04 07:23 UTC, Nicholassully commented on finance-api/internal/store/queries/finance_client.sql
> +SELECT id, reference, amount, raiseddate, cacheddebtamount FROM invoice WHERE finance_client_id = $1;
The invoice will be in this pr yes

2024-04-04 07:23 UTC, Nicholassully commented on finance-hub/internal/api/get_invoices_test.go
> +	//assert.Equal(t, expectedResponse, invoices)
done

2024-04-04 08:42 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +			ReceivedDate:    shared.Date{Time: i.Allocateddate.Time},
The shared struct is the contract between the front end and the back end, not the representation presented to the user. If we need to display data in a different way to how it is fetched, you will need to transform it into a different struct (see how it is done in `finance-hub/internal/server/fee_reductions.go`)

2024-04-04 08:46 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +	group.Go(func() error {
On second thought, why are you making two calls to the database here? If we want to fetch invoices along with their ledger allocations, can't we do it as a single query? We no longer have an ORM in charge of our queries.

2024-04-08 07:36 UTC, josephsmith0705 approved these changes

2024-04-08 08:42 UTC, merged