Pfs 51 supervision level backend
ministryofjustice/opg-sirius-supervision-finance-hub pull request #33
Opened 2024-04-08 13:27 UTC by Nicholassully

2024-04-09 15:02 UTC, denialanderror requested changes

2024-04-09 15:02 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +		return nil
Shouldn't this return an error?

2024-04-10 07:26 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +var totalOfLedgerAllocationsAmount int
If scope it any low I can use it in both the for loop on line 28 and in the method on line 74 in less I have missed a better way

2024-04-10 07:29 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +		return nil
I am not sure how I would be able to return an error as the invoice struct for ledgers only expect an array of allocations, happy to talk about it tho

2024-04-10 08:50 UTC, denialanderror requested changes

2024-04-10 08:50 UTC, denialanderror commented on migrations/000002_invoice_changers.down.sql
These will all need to change to the new migration format as we had to move from Golang-Migrate to Goose due to the former being poorly maintained.

2024-04-10 08:50 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +		return nil
If the query is incorrect or returns invalid data, this would silently fail and we would have no indication it was wrong until it failed for users in production. If the code cannot return an error, it has to be refactored so it can. We can't just ignore errors because they are hard to write.

Functions in Go can return multiple types. The `Store.GetLedgerAllocations` function two lines above does exactly that.

2024-04-10 08:50 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +func CheckForAllocation(bankDate pgtype.Date, datetime pgtype.Timestamp) shared.Date {
This is an oddly named function. `CheckForAllocation` implies it is going to return a boolean. Also, this should be lower case unless you are wanting to use this function outside of the module.

2024-04-10 08:50 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +var totalOfLedgerAllocationsAmount int
If you need the value in more than one place, have one of them supply it to the other, or calculate it independently. Global variables should only be used for constants.

2024-04-10 12:41 UTC, denialanderror requested changes

2024-04-10 12:41 UTC, denialanderror commented on Makefile
> -	docker compose -f docker-compose.yml -f docker/docker-compose.dev.yml run finance-migration
These shouldn't be removed.

2024-04-10 12:41 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +var totalOfLedgerAllocationsAmount int
This still needs removing.

2024-04-11 08:20 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +		return nil
Don't silently fail. This should also return an error if an error occurs.

2024-04-11 08:21 UTC, denialanderror commented on finance-hub/internal/server/invoices.go
> +	for _, f := range in {
`f` isn't a useful variable name. I don't mind single letter variables but they should at least be relevant to what they represent.

2024-04-11 08:22 UTC, denialanderror commented on finance-hub/internal/server/invoices.go
> +	for _, f := range in {
Same here

2024-04-11 08:23 UTC, denialanderror commented on finance-hub/internal/server/invoices.go
> +func transformSupervisionLevels(in []shared.SupervisionLevel) []SupervisionLevel {
These transform functions should be member functions of the handler, otherwise they will be in the module namespace.

2024-04-11 08:25 UTC, denialanderror commented on migrations/20240410094040_ledger_allocation_type.sql
> +ALTER TABLE ledger_allocation ADD COLUMN transaction_type varchar(250);
If you want to set varchar to its maximum (which presumably is what you are doing), you want varchar(255)

2024-04-11 08:28 UTC, denialanderror commented
Can you also take the data and routes out of json server, so there is no tidying up to do once we've done all the back end routes?

2024-04-11 10:09 UTC, Nicholassully commented on migrations/20240410094040_ledger_allocation_type.sql
> +ALTER TABLE ledger_allocation ADD COLUMN transaction_type varchar(250);
done

2024-04-11 10:09 UTC, Nicholassully commented on finance-hub/internal/server/invoices.go
> +	for _, f := range in {
done

2024-04-11 10:09 UTC, Nicholassully commented on finance-hub/internal/server/invoices.go
> +	for _, f := range in {
done

2024-04-11 10:09 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +		return nil
done

2024-04-11 13:48 UTC, denialanderror commented on migrations/20240410093925_invoice_changers.sql
This file should be renamed to detail what the migration does

2024-04-11 13:49 UTC, denialanderror commented on finance-api/internal/service/invoices_test.go
> +				assert.Empty(t, got)
This will assert as true if the test that is meant to return data returns nothing

2024-04-12 05:48 UTC, Nicholassully commented on migrations/20240410093925_invoice_changers.sql
> +ALTER TABLE invoice DROP COLUMN person_id;
They are columns that need to be dropped as will not be needed moving forward

2024-04-12 07:17 UTC, Nicholassully commented on finance-api/internal/service/invoices_test.go
> +				assert.Empty(t, got)
Need this for the second test as I can do a deep equal on an empty array. In less I have missed something

2024-04-12 07:17 UTC, Nicholassully commented on migrations/20240410093925_invoice_changers.sql
done

2024-04-12 08:54 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +	for _, i := range invoicesRawData {
Rename `i` please. It isn't the index.

2024-04-12 08:55 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +		log.Println(supervisionLevels)
multiple log statements

2024-04-12 08:55 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +	for _, i := range supervisionLevelsRawData {
Same here

2024-04-12 08:55 UTC, denialanderror commented on finance-api/internal/service/invoices.go
> +	for _, i := range ledgerAllocationsRawData {
And here

2024-04-12 08:57 UTC, denialanderror commented on finance-api/internal/service/invoices_test.go
> +				assert.Empty(t, got)
You'll need to think of a different way of doing it then. A test that passes on false positives isn't a test.

2024-04-12 09:05 UTC, denialanderror commented on migrations/20240410093925_invoice_changers.sql
> +ALTER TABLE invoice DROP COLUMN person_id;
Why are you dropping them in the down migration then? This will only run if the migration is rolled back.

2024-04-12 11:35 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +	for _, i := range ledgerAllocationsRawData {
done

2024-04-12 11:35 UTC, Nicholassully commented on finance-api/internal/service/invoices.go
> +	for _, i := range supervisionLevelsRawData {
done

2024-04-12 11:44 UTC, denialanderror commented on finance-api/internal/service/invoices_test.go
> +				assert.Empty(t, got)
How does this fix the issue? The first test case expects an array containing data. If the function is broken and returns an array containing no data, this test will still pass.

2024-04-12 17:40 UTC, denialanderror commented on migrations/20240410093925_invoice_created_fields.sql
> +ALTER TABLE invoice DROP COLUMN createdby_id;
This still needs changing. Down migrations are for rolling back, not for dropping columns. If you want to drop unused columns as part of a migration, they need to go in the Up section

2024-04-16 08:23 UTC, denialanderror approved these changes

2024-04-16 08:38 UTC, merged