Pfs 52 fee reductions backend
ministryofjustice/opg-sirius-supervision-finance-hub pull request #36
Opened 2024-04-10 06:37 UTC by Nicholassully

2024-04-11 07:05 UTC, Nicholassully commented on finance-api/internal/service/fee_reductions.go
> +	for _, i := range feeReductionsRawData {
done

2024-04-11 07:05 UTC, Nicholassully commented on finance-api/cmd/api/fee_reductions.go
> +		http.Error(w, err.Error(), http.StatusNotFound)
done

2024-04-11 07:05 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +order by enddate desc;
done

2024-04-11 07:05 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +           else 'Cancelled' end as status,
yes I have changed that as well

2024-04-11 08:34 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +           when (startdate < CURRENT_DATE and enddate > CURRENT_DATE) then 'Active'
move out of the sql

2024-04-12 09:16 UTC, denialanderror requested changes

2024-04-12 09:16 UTC, denialanderror commented on finance-api/internal/service/fee_reductions_test.go
> +				assert.Empty(t, got)
Same issue here as with the other PR

2024-04-12 17:43 UTC, denialanderror approved these changes

2024-04-16 09:54 UTC, denialanderror requested changes

2024-04-16 09:54 UTC, denialanderror commented on finance-api/internal/store/queries/fee_reductions.sql
> +where fr.finance_client_id = $1
Is this correct? The id we are sending down from the FE is the Sirius client ID, not the finance_client id.

2024-04-16 10:29 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +where fr.finance_client_id = $1
Good point changed

2024-04-16 10:40 UTC, denialanderror submitted a review, later dismissed

2024-04-16 10:50 UTC, denialanderror approved these changes

2024-04-16 10:53 UTC, merged