Pfs 21 fee form
ministryofjustice/opg-sirius-supervision-finance-hub pull request #44
Opened 2024-04-23 06:24 UTC by Nicholassully

2024-05-07 15:29 UTC, denialanderror requested changes

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +	_, err = s.Store.AddFeeReduction(ctx, addFeeReductionQueryArgs)
Even though you have started a transaction, I don't think you are actually associating any of these queries with one. According to the SQLC docs, after creating the transaction, you then need to pass it to the store e.g. `store := s.Store.WithTx(tx)`, and then you can use the `store` instead to be transaction-aware: https://docs.sqlc.dev/en/stable/howto/transactions.html

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +	_, err = s.Store.AddFeeReduction(ctx, addFeeReductionQueryArgs)
Is there a reason why you are returning something from this query but then ignoring it with `_`?

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/store/queries/invoice_fee_rangers.sql
> +-- name: GetInvoiceFeeRangersAmount :one
Rangers?

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/store/queries/invoices.sql
> +-- name: AddFeeReductionToInvoice :many
Should Invoice be plural?

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/testhelpers/test_db.go
> +	conn, err := pgx.Connect(ctx, connString)
Why are you creating a new connection? We already have a connection pool above.

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/store/queries/ledger.sql
> +VALUES (nextval('ledger_id_seq'::regclass), gen_random_uuid(), now(), $1, $2, $3, $4, 'Status', $5, null, $6, null,
Is `gen_random_uuid()` what we want for the reference?
Is "Status" what we want for the status?

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +			CreatedbyID:     pgtype.Int4{Int32: 1},
If you are going to add dummy values in as placeholders, please add TODO comments so they don't get missed when we go back to adding them.

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +func calculateEndDate(startYear string, lengthOfAward string) pgtype.Date {
These names are scoped to the `service` package, meaning anything in the service layer has access to them, so having them only able to calculate the start and end date in this particular instance impacts every other member of the package. 

They either need to be named to make them unique to fee reductions or generic so they can be reused by the whole package, with a preference for the latter.

2024-05-07 15:29 UTC, denialanderror commented on finance-api/internal/validation/validation.go
No tests for this

2024-05-07 15:29 UTC, denialanderror commented on finance-api/main.go
> +	vError := validation.New()
If the validation code is only being used in Payments (e.g. its not going to be moved to the `opg-go-common` library), there's no real need to be register the validations separately. Just move them inside the new function and make the register function lower case.

2024-05-08 14:56 UTC, Nicholassully commented on adrs/0010-validator.md
> +The library also offered away to do custom validation in a clear way.
done

2024-05-08 14:56 UTC, Nicholassully commented on cypress/e2e/add-fee-reduction.cy.js
> +    // it("shows correct success message", () => {
done

2024-05-08 14:57 UTC, Nicholassully commented on cypress/e2e/invoices.cy.js
> +        cy.contains('[data-cy="supervision-level-data"]', "GENERAL").first();
done

2024-05-08 14:57 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +	validationError := s.VError.ValidateStruct(body)
Ok cool I was trying to keep the validations together what if I check in the api what validation error is coming from the service and throw the correct status code to the front? (done)

2024-05-08 14:57 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +-- name: CheckForOverlappingFeeReduction :one
done

2024-05-08 14:57 UTC, Nicholassully commented on finance-api/cmd/api/server.go
> +	AddFeeReduction(body shared.AddFeeReduction) (shared.ValidationError, error)
done

2024-05-08 14:57 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +		if validationErrors["Overlap"] == nil {
I need it there I think as I was getting a runtime panic as the key would be nil so checking that its there makes go initialise it. (mute)

2024-05-08 14:57 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +		validationError.Message = "This has not worked"
Testing I can get rid of it

2024-05-08 14:57 UTC, Nicholassully commented on shared/validation.go
> +type ValidationError struct {
Removed the message. The api will send one validationError that can contain many validationErrors

2024-05-08 14:57 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +		Evidencetype: pgtype.Text{},
I believed it was with `evidencetype      varchar(255) default NULL::character varying,` (done)

2024-05-08 14:57 UTC, Nicholassully commented on shared/add_fee_reduction.go
> +	DateReceive       Date   `json:"dateReceived" validate:"required,date-in-the-past"`
done

2024-05-08 14:57 UTC, Nicholassully commented on shared/add_fee_reduction.go
> +	FeeReductionNotes string `json:"feeReductionNotes" validate:"required,thousand-character-limit"`
done

2024-05-08 14:57 UTC, Nicholassully commented on shared/add_fee_reduction.go
> +	ClientId          int    `json:"clientId"`
Yes thats right I just thought as I am sending the body it would be nicer all in one place (removed)

2024-05-08 14:58 UTC, Nicholassully commented on json-server/config/db.json
> +    {
nope done

2024-05-08 14:58 UTC, Nicholassully commented on finance-hub/internal/util/translate.go
> +	"DateReceive": {
done

2024-05-08 14:58 UTC, Nicholassully commented on finance-hub/internal/server/add_fee_reduction.go
> +type FormValues struct {
done

2024-05-08 14:58 UTC, Nicholassully commented on shared/add_fee_reduction.go
> +	LengthOfAward     string `json:"lengthOfAward" validate:"required"`
done

2024-05-08 14:58 UTC, Nicholassully commented on finance-hub/internal/server/update_fee_reduction.go
> +type UpdateFeeReductionHandler struct {
done

2024-05-08 14:58 UTC, Nicholassully commented on finance-hub/internal/api/api_client.go
> +	Errors  ValidationErrors `json:"validation_errors"`
Moved to shared

2024-05-08 14:58 UTC, Nicholassully commented on finance-api/internal/service/service.go
> +	VError *validation.Validate
done

2024-05-08 14:58 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +	_, err = s.Store.AddFeeReduction(ctx, addFeeReductionQueryArgs)
done

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +	_, err = s.Store.AddFeeReduction(ctx, addFeeReductionQueryArgs)
I need the id and must of _ be mistake have changed that now

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/store/queries/invoice_fee_rangers.sql
> +-- name: GetInvoiceFeeRangersAmount :one
done

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/store/queries/invoices.sql
> +-- name: AddFeeReductionToInvoice :many
done

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/store/queries/ledger.sql
> +VALUES (nextval('ledger_id_seq'::regclass), gen_random_uuid(), now(), $1, $2, $3, $4, 'Status', $5, null, $6, null,
looking at Sirius code the reference is random and status is not part of this ticket but I thought I would just leave it as status

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +			CreatedbyID:     pgtype.Int4{Int32: 1},
done

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +func calculateEndDate(startYear string, lengthOfAward string) pgtype.Date {
done

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/main.go
> +	vError := validation.New()
need help

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/validation/validation.go
need help

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/internal/testhelpers/test_db.go
> +	conn, err := pgx.Connect(ctx, connString)
I needed DbConn     *pgx.Conn for the tests need help

2024-05-08 14:59 UTC, Nicholassully commented on finance-api/cmd/api/add_fee_reduction.go
need help

2024-05-08 15:00 UTC, Nicholassully commented on finance-hub/internal/api/add_fee_reduction_test.go
> +//func TestAddFeeReductionUnauthorised(t *testing.T) {
need to ask about this

2024-05-09 08:04 UTC, Nicholassully commented on finance-hub/internal/api/add_fee_reduction_test.go
> +//func TestAddFeeReductionUnauthorised(t *testing.T) {
done

2024-05-09 08:04 UTC, Nicholassully commented on finance-api/cmd/api/add_fee_reduction.go
done

2024-05-09 12:42 UTC, Nicholassully commented on finance-api/internal/validation/validation.go
done

2024-05-09 12:42 UTC, Nicholassully commented on finance-api/main.go
> +	vError := validation.New()
done

2024-05-10 10:00 UTC, denialanderror requested changes

2024-05-10 10:00 UTC, denialanderror commented on finance-api/internal/validation/validation.go
> +			validationErrors[field][tag] = fmt.Sprintf("This field %s needs to be looked at %s", field, tag)
I don't understand what this message is for. It doesn't ever appear to be parsed, and the field and tag are already encoded in the struct.

2024-05-10 11:58 UTC, Nicholassully commented on cypress/e2e/add-fee-reduction.cy.js
> +        cy.get('.moj-banner__message').contains("The hardship has been successfully add")
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-api/cmd/api/add_fee_reduction.go
> +		// Write the JSON response body
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-api/internal/store/queries/invoice_fee_ranger.sql
meant to be range changed

2024-05-10 11:58 UTC, Nicholassully commented on finance-api/internal/validation/validation.go
> +	_ = v.RegisterValidation("date-in-the-past", ValidateDateInThePast)
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-api/internal/validation/validation.go
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-hub/cypress.config.js
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-hub/internal/api/add_fee_reduction.go
> +	dateReceivedTransformed, _ := time.Parse("2006-01-02", dateReceived)
The NewDate func wants it in a different format and throw a panic

2024-05-10 11:58 UTC, Nicholassully commented on finance-hub/internal/api/add_fee_reduction_test.go
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-hub/internal/api/api_client.go
done

2024-05-10 11:58 UTC, Nicholassully commented on finance-hub/internal/server/submit_fee_reduction.go
> +			FeeType:       r.PostFormValue("feeType"),
done

2024-05-10 11:58 UTC, Nicholassully commented on shared/validation.go
> +//}
done

2024-05-10 11:58 UTC, Nicholassully commented on shared/validation.go
> +	return "unexpected response from Sirius"
done

2024-05-10 11:58 UTC, Nicholassully commented on shared/validation.go
> +type StatusError struct {
to keep all the error things together. Do you want me to do a file in Util name `errorStatus.go`? Would that be a better approach?

2024-05-10 11:59 UTC, Nicholassully commented on finance-api/internal/validation/validation.go
> +			validationErrors[field][tag] = fmt.Sprintf("This field %s needs to be looked at %s", field, tag)
I thought just in case that someone else uses the api at least there is a message if they are not translating it

2024-05-10 11:59 UTC, Nicholassully commented on finance-hub/web/template/add-fee-reduction.gotmpl
> +                            <input class="govuk-input" id="startDateYear" name="startDateYear" style="width: 40%" type="text" {{ if ne .FeeReductionFormValues.StartYear "" }}value="{{.FeeReductionFor
Changed just to be a number field

2024-05-10 12:37 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +		return errors.New("overlap")
done

2024-05-10 13:57 UTC, Nicholassully commented on shared/add_fee_reduction.go
> +	DateReceived  Date   `json:"dateReceived" validate:"date-in-the-past"`
done

2024-05-10 14:00 UTC, denialanderror commented on finance-hub/web/template/add-fee-reduction.gotmpl
> +                                <div id="f-FeeType" class="govuk-form-group {{ if index .AppVars.Errors "FeeType" }}govuk-form-group--error{{ end }}">
Why is every form field wrapped in multiple divs with identical classes?

2024-05-10 14:10 UTC, denialanderror commented on finance-hub/web/template/add-fee-reduction.gotmpl
> +                            <label class="govuk-label" for="date">
Incorrect labelling here. Same on received date.

2024-05-10 14:22 UTC, Nicholassully commented on finance-hub/web/template/add-fee-reduction.gotmpl
> +                            <label class="govuk-label" for="date">
done

2024-05-14 10:56 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +				Supervisionlevel: "GENERAL",
Are fee reductions always added with a General supervision level?

2024-05-14 10:59 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +				//TODO make sure we have correct createdby ID
Create a ticket for doing this and add the ticket number into the todo, otherwise this will get missed.

2024-05-14 11:10 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction_test.go
> +func TestService_AddFeeReduction(t *testing.T) {
All this test is testing is that no error is returned. This implementation would also pass this test:
```func (s *Service) AddFeeReduction(id int, data shared.AddFeeReduction) error {
return nil```
This test should at the very least check that the expected rows have been entered into the database.

2024-05-14 11:13 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction_test.go
> +func TestService_AddFeeReductionOverlap(t *testing.T) {
This test needs to be far more comprehensive.  Tests should cover all edge cases.

2024-05-14 11:15 UTC, denialanderror commented on finance-api/internal/store/queries/invoice_fee_range.sql
> +-- name: GetInvoiceFeeRangerAmount :one
This is still called "ranger"

2024-05-14 11:19 UTC, denialanderror commented on finance-api/internal/validation/validation.go
> +	_ = v.RegisterValidation("date-in-the-past", ValidateDateInThePast)
You've now removed all error checking here. If we try to create the validator at start up and it fails to register these validations, we don't want to just ignore it and carry on as if nothing happened. This should be a fatal error.

2024-05-14 11:20 UTC, denialanderror commented on finance-api/internal/validation/validation.go
> +			validationErrors[field][tag] = fmt.Sprintf("This field %s needs to be looked at %s", field, tag)
But that information is already encoded in the error. The field and tag detail the field that failed and the reason for failing. The message is redundant.

2024-05-14 11:27 UTC, denialanderror commented on finance-api/internal/validation/validation.go
> +			validationErrors[field][tag] = fmt.Sprintf("This field %s needs to be looked at %s", field, tag)
The message is redundant, whether they are translating or not, as the information is encoded in the field and tag. Leave it as it is and I will refactor it in my PR.

2024-05-14 11:30 UTC, denialanderror commented on finance-hub/internal/api/add_fee_reduction.go
> +		return shared.ValidationError{Errors: shared.ValidationErrors{"Overlap": {"StartOrEndDate": ""}}}
This error won't show if it is returned alongside validation errors (presumably you would want to display them together?)

2024-05-14 11:34 UTC, denialanderror commented on finance-hub/web/template/add-fee-reduction.gotmpl
> +                                <div id="f-FeeType" class="govuk-form-group {{ if index .AppVars.Errors "FeeType" }}govuk-form-group--error{{ end }}">
This still needs resolving, see lines 23-25. Same with the other fields.

2024-05-14 11:37 UTC, denialanderror commented on shared/validation.go
> +func (e ClientError) Error() string {
Not sure why this has been moved in here. The shared package is for code that is shared between the two services and this is only used in the Hub.  Unauthorised responses from the API will use the 403 status code.

2024-05-14 11:39 UTC, denialanderror commented
You still have multiple Cypress files in the Hub package that will never be used. Please remove them.

2024-05-14 13:17 UTC, Nicholassully commented on shared/validation.go
> +func (e ClientError) Error() string {
moved back and changed

2024-05-14 13:17 UTC, Nicholassully commented on finance-hub/internal/api/add_fee_reduction.go
> +		return shared.ValidationError{Errors: shared.ValidationErrors{"Overlap": {"StartOrEndDate": ""}}}
The validation on the struct will happen first before checking the overlap after so they will not happen at the same time that I can think of

2024-05-14 13:17 UTC, Nicholassully commented on finance-api/internal/store/queries/invoice_fee_range.sql
> +-- name: GetInvoiceFeeRangerAmount :one
done

2024-05-14 13:17 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +				//TODO make sure we have correct createdby ID
Ticket PFS-88 has been made

2024-05-14 13:17 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +				Supervisionlevel: "GENERAL",
For remissions we need to look at the supervision level but for the other two its just the whole invoice amount.

2024-05-14 13:22 UTC, denialanderror commented on finance-hub/internal/api/add_fee_reduction.go
> +		return ErrUnauthorized
Not sure I understand this. Why does it check for forbidden status and then return unauthorized? They are different things.

2024-05-14 13:25 UTC, Nicholassully commented on finance-hub/internal/api/add_fee_reduction.go
> +		return ErrUnauthorized
As this was the pattern we had in other hubs so thought that is what we would want here 🤔

2024-05-14 14:04 UTC, Nicholassully commented on finance-api/internal/validation/validation.go
> +	_ = v.RegisterValidation("date-in-the-past", ValidateDateInThePast)
done

2024-05-14 14:04 UTC, Nicholassully commented on finance-hub/web/template/add-fee-reduction.gotmpl
> +                                <div id="f-FeeType" class="govuk-form-group {{ if index .AppVars.Errors "FeeType" }}govuk-form-group--error{{ end }}">
done

2024-05-14 14:43 UTC, denialanderror approved these changes

2024-05-14 15:13 UTC, merged