pfs-9 adding client information #minor
ministryofjustice/opg-sirius-supervision-finance-hub pull request #5
Opened 2024-02-08 09:58 UTC by Nicholassully

2024-02-08 11:48 UTC, denialanderror requested changes

2024-02-08 11:48 UTC, denialanderror commented on cypress/e2e/finance_hub.cy.js
> +            cy.get('#hook-person-name').should("contain", "Finance Person");
You should use `data-cy` attributes instead of ids if that is how you are wanting to address elements. ids are for CSS and JS, not testing.

Even better, don't address elements by id/attribute at all and do it how a user would: by text.

2024-02-08 11:48 UTC, denialanderror commented on cypress/e2e/finance_hub.cy.js
> +        cy.setCookie("XSRF-TOKEN", "abcde");
We don't need an xsrf token here. There are no forms being submitted.

2024-02-08 11:48 UTC, denialanderror commented on go.mod
> +	github.com/gorilla/mux v1.8.1
What's mux being used for? This is a library that was deprecated and then undeprecated. If we want a web framework over the native http library, there are better, more stable options.

2024-02-08 11:48 UTC, denialanderror commented on internal/server/finance_vars.go
> +	FinancePerson   model.FinancePerson
This can just be called "Person", or better, "Client". There isn't any other type of person here.

2024-02-08 11:48 UTC, denialanderror commented on json-server/config/routes.json
> +    "/finance/:id": "/finance"
You don't need to put in custom routing here. json-server will take a route and look in the data structure for the array matching that path and the object with that id. Structure the data better rather than adding in custom routes for everything, otherwise the db.json gets very messy, very quickly. https://github.com/typicode/json-server

2024-02-08 11:48 UTC, denialanderror commented on json-server/config/db.js
This should be a json file unless there is a good reason for it needing javascript

2024-02-08 11:48 UTC, denialanderror commented on web/assets/scss/finance-hub.scss
Is this the same for all our hubs? If so, we should look to extract it as a package somewhere (not as part of this, we'll create a ticket).

2024-02-08 11:48 UTC, denialanderror commented on web/template/invoices.gotmpl
These templates should have type annotations

2024-02-08 11:48 UTC, denialanderror commented on internal/server/finance_vars_test.go
Why was this test deleted?

2024-02-08 11:48 UTC, denialanderror commented on internal/sirius/get_finance_person_details.go
There doesn't appear to be a test for this

2024-02-09 08:27 UTC, Nicholassully commented on cypress/e2e/finance_hub.cy.js
> +            cy.get('#hook-person-name').should("contain", "Finance Person");
done

2024-02-09 08:27 UTC, Nicholassully commented on cypress/e2e/finance_hub.cy.js
> +        cy.setCookie("XSRF-TOKEN", "abcde");
done

2024-02-09 08:27 UTC, Nicholassully commented on go.mod
> +	github.com/gorilla/mux v1.8.1
removed

2024-02-09 08:27 UTC, Nicholassully commented on internal/server/finance_vars.go
> +	FinancePerson   model.FinancePerson
done

2024-02-09 08:27 UTC, Nicholassully commented on json-server/config/routes.json
> +    "/finance/:id": "/finance"
done

2024-02-09 08:27 UTC, Nicholassully commented on json-server/config/db.js
done

2024-02-09 08:27 UTC, Nicholassully commented on web/assets/scss/finance-hub.scss
Yes it looks like this is the same in deputy and firm hubs

2024-02-09 08:28 UTC, Nicholassully commented on web/template/invoices.gotmpl
done

2024-02-09 08:28 UTC, Nicholassully commented on internal/server/finance_vars_test.go
It was by mistake

2024-02-09 08:28 UTC, Nicholassully commented on internal/sirius/get_finance_person_details.go
added

2024-02-09 09:24 UTC, josephsmith0705 commented on web/template/layout/page.gotmpl
> -        <main class="govuk-main-wrapper app-main-class" id="main-content" role="main">
Just FYI, we use this id="main-content" usually to include a skip link for accessibility purposes. It's not a huge deal removing this here as we haven't got a skip link in this system yet anyway, but all gov.uk sites are meant to have one so might be worth keeping this in if we're expecting to add it in before this goes live anyway.
https://design-system.service.gov.uk/components/skip-link/

2024-02-09 09:24 UTC, josephsmith0705 approved these changes

2024-02-13 07:53 UTC, merged