Pfs 40 approve pending invoice adjustment
ministryofjustice/opg-sirius-supervision-finance-hub pull request #62
Opened 2024-05-20 12:35 UTC by Nicholassully

2024-05-20 16:07 UTC, josephsmith0705 submitted a review, later dismissed

2024-05-21 14:29 UTC, denialanderror requested changes

2024-05-21 14:29 UTC, denialanderror commented on cypress/e2e/pending-invoice-adjustments.cy.js
> +//     });
Is this meant to be here?

2024-05-21 14:29 UTC, denialanderror commented on finance-api/cmd/api/server.go
> +	http.HandleFunc("POST /clients/{id}/invoice-adjustments/{ledgerId}", s.updatePendingInvoiceAdjustment)
If this is updating an existing resource, it should be a PUT, not a POST

2024-05-21 14:29 UTC, denialanderror commented on finance-api/internal/store/queries/ledger_allocation.sql
> +-- returning ledger_allocation.*;
Commented out code

2024-05-21 14:29 UTC, denialanderror commented on finance-api/internal/service/update_pending_invoice_adjustment.go
> +	_, err = transaction.UpdateLedgerAllocationAdjustment(ctx, ledgerIdTransformed)
If you are always throwing away the returned values, why do you return them?

2024-05-21 14:29 UTC, denialanderror commented on finance-api/internal/store/queries/ledger_allocation.sql
> +returning ledger_allocation.*;
This is exactly the same query as the one in `ledger.sql`

2024-05-21 14:29 UTC, denialanderror commented on finance-hub/internal/api/update_pending_invoice_adjustment.go
> +	req, err := c.newBackendRequest(ctx, http.MethodPost, url, nil)
Should be a PUT

2024-05-21 14:29 UTC, denialanderror commented on finance-api/cmd/api/update_pending_invoice_adjustment.go
> +	w.WriteHeader(http.StatusOK)
We are not returning any data here, so the content-type is not needed and it should really return a 204 if we are being _reaaaaaally_ picky

2024-05-21 14:29 UTC, denialanderror commented on finance-hub/internal/server/pending_invoice_adjustments.go
> +			ClientId:         clientId,
Is it necessary to add the client ID to every adjustment? Couldn't this just be on the top level vars and accessed from there?

2024-05-23 07:15 UTC, Nicholassully commented on finance-hub/internal/server/pending_invoice_adjustments.go
> +			ClientId:         clientId,
Moved it out

2024-05-23 07:15 UTC, Nicholassully commented on finance-api/cmd/api/update_pending_invoice_adjustment.go
> +	w.WriteHeader(http.StatusOK)
Ok changed

2024-05-23 07:15 UTC, Nicholassully commented on finance-hub/internal/api/update_pending_invoice_adjustment.go
> +	req, err := c.newBackendRequest(ctx, http.MethodPost, url, nil)
done

2024-05-23 07:15 UTC, Nicholassully commented on finance-api/internal/store/queries/ledger_allocation.sql
> +returning ledger_allocation.*;
It was and have changed it

2024-05-23 07:15 UTC, Nicholassully commented on finance-api/internal/service/update_pending_invoice_adjustment.go
> +	_, err = transaction.UpdateLedgerAllocationAdjustment(ctx, ledgerIdTransformed)
Good point changed

2024-05-23 07:15 UTC, Nicholassully commented on finance-api/cmd/api/server.go
> +	http.HandleFunc("POST /clients/{id}/invoice-adjustments/{ledgerId}", s.updatePendingInvoiceAdjustment)
done

2024-05-23 07:15 UTC, Nicholassully commented on cypress/e2e/pending-invoice-adjustments.cy.js
> +//     });
no and gone

2024-05-23 09:26 UTC, denialanderror approved these changes

2024-05-23 09:27 UTC, merged