PFS-71 Create reject pending invoice adjustment functionality
ministryofjustice/opg-sirius-supervision-finance-hub pull request #67
Opened 2024-05-23 12:04 UTC by josephsmith0705

2024-05-23 13:52 UTC, josephsmith0705 commented on Makefile
> +cypress: setup-directories clean start-and-seed
Take down the current containers, otherwise trying to seed will cause errors as primary keys already exist

2024-06-03 09:21 UTC, denialanderror requested changes

2024-06-03 09:21 UTC, denialanderror commented on finance-api/cmd/api/update_pending_invoice_adjustment.go
> +	}
If you move this struct into the shared package, you can then add validation to it, such as `oneof` to guard against values other than approved or rejected.

2024-06-03 09:21 UTC, denialanderror commented on finance-hub/internal/server/submit_reject_pending_invoice_adjustment.go
I think this and the approve handlers can be combined and just pass through the status in the URL instead of having a whole new handler for it

2024-06-03 09:21 UTC, denialanderror commented on finance-hub/internal/server/submit_reject_pending_invoice_adjustment.go
> +		status      = "rejected"
Personally, I'd prefer the status to be passed around in upper case, which generally signifies its a constant and a placeholder.

2024-06-04 08:52 UTC, denialanderror requested changes

2024-06-04 08:52 UTC, denialanderror commented on finance-hub/internal/server/route.go
> +		return "You have rejected the write off"
Debit adjustments now exist as well. Looks like I missed adding in the approve message so could you add both approve and reject for debit here please?

2024-06-04 08:52 UTC, denialanderror commented on finance-hub/internal/api/update_pending_invoice_adjustment_test.go
> +	err := client.UpdatePendingInvoiceAdjustment(getContext(nil), 1, 2, "approved")
Can you change all the instances in tests where we are using "approved" to "APPROVED", as that is the actual expected value now? Doesn't make a difference for the tests but it may save some confusion in the future.

2024-06-04 08:52 UTC, denialanderror commented on finance-hub/internal/server/submit_approve_pending_invoice_adjustment.go
Can you delete this file now?

2024-06-04 09:54 UTC, denialanderror approved these changes

2024-06-04 09:54 UTC, merged