pfs-38 adding a manual invoice
ministryofjustice/opg-sirius-supervision-finance-hub pull request #80
Opened 2024-06-13 09:15 UTC by Nicholassully

2024-06-13 15:52 UTC, denialanderror requested changes

2024-06-13 15:52 UTC, denialanderror commented on cypress/e2e/add-manual-invoice.cy.js
> +        cy.setCookie("fail-route", "addManualInvoiceError");
This does nothing. The response isn't coming from json-server

2024-06-13 15:52 UTC, denialanderror commented on cypress/e2e/add-manual-invoice.cy.js
> +    });
Could you also stick in a check for the invoice being correctly added in the invoice list? We need to start thinking of our Cypress tests more holistically as end-to-end user journeys as opposed to UI tests.

2024-06-13 15:52 UTC, denialanderror commented on cypress/e2e/add-manual-invoice.cy.js
> +        cy.get('#invoice-type').select('SO');
Where possible, avoid using ids for selectors. Address form fields by their labels.

2024-06-13 15:52 UTC, denialanderror commented on cypress/e2e/invoices.cy.js
> +            cy.contains('[data-cy="invoice-raised-date"]',"16/03/2020").first();
What does `.first()` do here?

2024-06-13 15:52 UTC, denialanderror commented on finance-api/cmd/api/server.go
> +	http.HandleFunc("POST /clients/{clientId}/manual-invoice", s.addManualInvoice)
This should be `/clients/{clientId}/invoices`. manual-invoice is an instruction, not a resource, and this is a REST API, so you address by resource.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_fee_reduction.go
> +		if err2 != nil {
If you are creating new error vars instead of reusing the existing one (fine if you do), name them something useful

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +	validInvoiceTypesRaisedDateInPast := []string{
Move this onto the enum struct. That's part of the reason we have enums in the first place. e.g. `func (i InvoiceType) isRaisedDateValid(rd Date) bool` and then switch on the types you want to validate on.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +	if !isSameFinancialYear(startDate, endDate) {
This can never happen if you are validating the start date first.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/store/queries/invoices.sql
> +-- name: GetInvoiceRefCount :one
This is never used

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +	hasCounterGotInvoiceRefYear, err := transaction.CheckCounterForInvoiceRefYear(ctx, strconv.Itoa(data.StartDate.Time.Year())+"InvoiceNumber")
You could squash the checking, creating, and updating into a single query with upserts: https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +		Source:            pgtype.Text{String: "Created manually", Valid: true},
Is this the value we want?

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +func (s *Service) AddManualInvoice(id int, data shared.AddManualInvoice) error {
Rename id to clientId to make it clear what it refers to

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +type BadRequests struct {
Move these to service.go.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +	feeReductionId, _ := transaction.AddFeeReductionToInvoice(ctx, AddFeeReductionToInvoiceParams)
Why do you fetch the fee reductions first before calling this query? If you pass in the client ID instead, you can get the fee reductions in this query.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +		err2 := s.AddLedgerAndAllocations(feeReduction.Type, feeReduction.ID, feeReduction.FinanceClientID.Int32, invoice, transaction, ctx)
Again, why fetch the fee reduction from the database only to pass those values into another query to the database? Pass in the id and then join on the table that way.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +	}
Wouldn't it be easier to check the length of strNumber and then add enough zeros to make it the right number of characters, rather than adding six zeros and then potentially removing them all again?

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +func isSameFinancialYear(startDate *shared.Date, endDate *shared.Date) bool {
Move this function onto the Date struct.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +func contains(slice []string, value string) bool {
Use `slices.contains`

2024-06-13 15:52 UTC, denialanderror commented on finance-hub/internal/server/update_manual_invoice.go
> +type InvoiceType struct {
Is this used?

2024-06-13 15:52 UTC, denialanderror commented on finance-hub/internal/server/submit_manual_invoice.go
> +		raisedDate = raisedDateYear + "-0" + raisedDateMonth + "-" + raisedDateDay
Wouldn't this break if the raisedDateMonth was November or December?

2024-06-13 15:52 UTC, denialanderror commented on finance-hub/internal/server/submit_manual_invoice.go
> +	switch invoiceType {
This switch needs unit testing

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/store/queries/ledger_allocation.sql
> +VALUES (NEXTVAL('ledger_allocation_id_seq'::REGCLASS), $1, $2, NOW(), $3, 'APPROVED', NULL, NULL, NULL, NULL, NULL,
I don't think this is correct as APPROVED isn't a ledger allocation status, but leave it as it is as there is another ticket to investigate.

2024-06-13 15:52 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +		FeeReductionID:    pgtype.Int4{},
Why are all these values being passed in empty when they could just be nulls in the query?

2024-06-14 13:50 UTC, Nicholassully commented on cypress/e2e/add-manual-invoice.cy.js
> +        cy.setCookie("fail-route", "addManualInvoiceError");
done

2024-06-14 13:50 UTC, Nicholassully commented on cypress/e2e/add-manual-invoice.cy.js
> +    });
done

2024-06-14 13:50 UTC, Nicholassully commented on cypress/e2e/add-manual-invoice.cy.js
> +        cy.get('#invoice-type').select('SO');
done

2024-06-14 13:50 UTC, Nicholassully commented on cypress/e2e/invoices.cy.js
> +            cy.contains('[data-cy="invoice-raised-date"]',"16/03/2020").first();
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/cmd/api/server.go
> +	http.HandleFunc("POST /clients/{clientId}/manual-invoice", s.addManualInvoice)
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +		if err2 != nil {
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +	validInvoiceTypesRaisedDateInPast := []string{
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +	if !isSameFinancialYear(startDate, endDate) {
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/store/queries/invoices.sql
> +-- name: GetInvoiceRefCount :one
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +	hasCounterGotInvoiceRefYear, err := transaction.CheckCounterForInvoiceRefYear(ctx, strconv.Itoa(data.StartDate.Time.Year())+"InvoiceNumber")
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +		Source:            pgtype.Text{String: "Created manually", Valid: true},
It is currently what they have in blue Sirius

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +func (s *Service) AddManualInvoice(id int, data shared.AddManualInvoice) error {
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +type BadRequests struct {
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +	feeReductionId, _ := transaction.AddFeeReductionToInvoice(ctx, AddFeeReductionToInvoiceParams)
done

2024-06-14 13:50 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +		err2 := s.AddLedgerAndAllocations(feeReduction.Type, feeReduction.ID, feeReduction.FinanceClientID.Int32, invoice, transaction, ctx)
I want more then the ID and think its clearer just to grab it from the DB and show it in the code

2024-06-14 13:51 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +	}
done

2024-06-14 13:51 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +func isSameFinancialYear(startDate *shared.Date, endDate *shared.Date) bool {
done

2024-06-14 13:51 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +func contains(slice []string, value string) bool {
done

2024-06-14 13:51 UTC, Nicholassully commented on finance-hub/internal/server/update_manual_invoice.go
> +type InvoiceType struct {
done

2024-06-14 13:51 UTC, Nicholassully commented on finance-hub/internal/server/submit_manual_invoice.go
> +		raisedDate = raisedDateYear + "-0" + raisedDateMonth + "-" + raisedDateDay
The Month and day are set and can only be 03 and 31 but good point I have changed it to not even look at whats coming in from the frontend

2024-06-14 13:51 UTC, Nicholassully commented on finance-hub/internal/server/submit_manual_invoice.go
> +	switch invoiceType {
done

2024-06-14 13:51 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +		FeeReductionID:    pgtype.Int4{},
done

2024-06-17 10:05 UTC, denialanderror commented on finance-hub/internal/api/add_manual_invoice.go
> +		raisedDateTransformed = &shared.Date{Time: raisedDateToTime}
shared.Date has a NewDate function that takes a string, so there is no need to transform it first.

2024-06-17 10:26 UTC, denialanderror commented on finance-api/internal/service/service.go
> +type BadRequests struct {
Move this into `shared.error`. You can then add an `unmarshal` function if you are having difficulties unmarshalling it as a []byte the other side.

2024-06-17 14:24 UTC, Nicholassully commented on shared/date.go
> +func (d Date) IsSameFinancialYear(d1 *Date) bool {
done

2024-06-17 14:24 UTC, Nicholassully commented on finance-hub/internal/api/add_manual_invoice.go
> +		if err := json.Unmarshal([]byte(bodyString), &badRequest); err != nil {
I was doing that so i could get rid of the "\n" from the body

2024-06-17 14:24 UTC, Nicholassully commented on finance-hub/internal/api/add_manual_invoice.go
> +		raisedDateTransformed = &shared.Date{Time: raisedDateToTime}
Have tried this from the feedback and the value passed into NewDate is in the wrong format I could convert it but then I feels like I am doing the same thing as I was doing.

2024-06-17 14:24 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
> +		err = s.AddLedgerAndAllocations(feeReduction.Type, feeReduction.ID, feeReduction.FinanceClientID.Int32, invoice, transaction, ctx)
I think for the small request to the DB it makes the sql easier to understand. Can we keep it this way?

2024-06-17 14:24 UTC, Nicholassully commented on finance-api/internal/service/service.go
> +type BadRequests struct {
done

2024-06-18 05:44 UTC, Nicholassully commented on finance-api/internal/service/add_fee_reduction.go
> +		if err2 != nil {
done

2024-06-18 08:25 UTC, Nicholassully commented on finance-hub/internal/api/add_manual_invoice.go
> +		if err := json.Unmarshal([]byte(bodyString), &badRequest); err != nil {
done

2024-06-18 08:25 UTC, Nicholassully commented on finance-hub/internal/api/add_manual_invoice.go
> +		raisedDateTransformed = &shared.Date{Time: raisedDateToTime}
done

2024-06-18 08:44 UTC, denialanderror requested changes

2024-06-18 08:44 UTC, denialanderror commented on finance-hub/internal/api/add_manual_invoice.go
> +type BadRequest struct {
Is this still used?

2024-06-18 08:44 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
> +		err = s.AddLedgerAndAllocations(feeReduction.Type, feeReduction.ID, feeReduction.FinanceClientID.Int32, invoice, transaction, ctx)
If you don't want to join within the query, just have `AddFeeReductionToInvoice` return the fields you need instead. It is already returning the id.

2024-06-18 09:01 UTC, Nicholassully commented on finance-hub/internal/api/add_manual_invoice.go
> +type BadRequest struct {
done

2024-06-18 13:17 UTC, denialanderror commented on finance-api/internal/service/add_manual_invoice.go
>  	feeReductionId, _ := transaction.AddFeeReductionToInvoice(ctx, AddFeeReductionToInvoiceParams)
Rename feeReductionId, as that isn't want this contains any more

2024-06-18 13:53 UTC, Nicholassully commented on finance-api/internal/service/add_manual_invoice.go
>  	feeReductionId, _ := transaction.AddFeeReductionToInvoice(ctx, AddFeeReductionToInvoiceParams)
good point

2024-06-19 10:02 UTC, denialanderror approved these changes

2024-06-25 14:10 UTC, denialanderror commented on finance-hub/internal/server/submit_manual_invoice.go
> +		endDate = raisedDate
I'm assuming this came out of demo feedback but what was the reason for this change?

2024-06-25 14:17 UTC, Nicholassully commented on finance-hub/internal/server/submit_manual_invoice.go
> +		endDate = raisedDate
Aye it was indeed. Alex said that its fine to be the same day for all of them as thats how long the invoice is charged for one day.

2024-06-25 14:20 UTC, denialanderror commented on finance-api/internal/store/queries/invoices.sql
> +-- name: GetInvoiceValidForFeeReduction :one
This returns fee reduction data, not invoice as the name suggests. `GetFeeReductionByInvoiceId`?

2024-06-25 14:28 UTC, denialanderror approved these changes

2024-07-01 14:15 UTC, denialanderror requested changes

2024-07-01 14:15 UTC, denialanderror commented on finance-api/internal/store/queries/fee_reductions.sql
> +-- name: GetFeeReductionByInvoiceId :one
Is that what this query is doing?

2024-07-01 14:15 UTC, denialanderror commented on finance-api/internal/store/queries/fee_reductions.sql
> +                         JOIN finance_client fc on fere.finance_client_id = fc.id
What's this subselect for? You are already joining the invoice to the fee reduction by finance client id, so doing a separate subselect to join back onto the table is very inefficient. Just join to the finance_client table in the main query.

2024-07-01 14:32 UTC, Nicholassully commented on shared/invoice_type.go
> +func (i InvoiceType) IsRaisedDateValid() bool {
done

2024-07-01 14:32 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +-- name: GetFeeReductionByInvoiceId :one
done

2024-07-01 14:32 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +                         JOIN finance_client fc on fere.finance_client_id = fc.id
done

2024-07-02 12:55 UTC, denialanderror requested changes

2024-07-02 12:55 UTC, denialanderror commented on finance-api/internal/store/queries/fee_reductions.sql
> +-- name: GetFeeReductionByClientIdAndInvoiceId :one
This still isn't what the query is doing. It is returning the fee reduction only if it is within a date range. Giving it a name of `...ByClientIdAndInvoiceId` gives the impression that it will return any fee reduction linked to the client and invoice, but this doesn't. The invoice ID is event irrelevant to what is being returned, as that is only being used to work out the date range.

I'd suggest refactoring the invoice out of this. What you are actually wanting is the raised date, which you already have as you just created the invoice with it. Pass in the client id and raised date and make it a generic query `GetFeeReductionForDate`.

2024-07-02 13:48 UTC, Nicholassully commented on finance-api/internal/store/queries/fee_reductions.sql
> +-- name: GetFeeReductionByClientIdAndInvoiceId :one
Good point indeed removed

2024-07-03 13:54 UTC, denialanderror submitted a review, later dismissed

2024-07-04 07:33 UTC, sixdaysandy approved these changes

2024-07-04 07:36 UTC, merged