pfs-58 sqlc vet into git actions
ministryofjustice/opg-sirius-supervision-finance-hub pull request #95
Opened 2024-07-02 12:20 UTC by Nicholassully

2024-07-02 14:16 UTC, denialanderror requested changes
There's not too much value adding vetting in if there is only one rule. See if there are other Postgres best practices you can enforce.

Also, the one rule that would add the most value is not being used: [sqlc-db-prepare](https://docs.sqlc.dev/en/latest/howto/vet.html#sqlc-db-prepare)

2024-07-02 14:16 UTC, denialanderror commented on finance-api/internal/store/sqlc.yaml
> +  - name: check-num-of-params
`check` is redundant. Also, name the rule to it is clear what has broken it. `num-of-params` doesn't tell me if I have too many or too few.

2024-07-02 14:16 UTC, denialanderror commented on finance-api/internal/store/sqlc.yaml
> +    message: "do you need all the parameters"
Failing the vetting fails the build, so the message has to be a failure statement, not a question. If the answer to "do you need all the parameters" was "yes", the build is still going to fail!

2024-07-02 14:16 UTC, denialanderror commented on finance-api/internal/store/sqlc.yaml
> +      query.params.size() > 7
Is there a reason why you've gone for 7?

2024-07-03 05:56 UTC, Nicholassully commented on finance-api/internal/store/sqlc.yaml
> +      query.params.size() > 7
We have an insert that needs 6 params and I wanted to add in an example of a rule for when we decide what we need.

2024-07-04 12:44 UTC, denialanderror requested changes

2024-07-04 12:44 UTC, denialanderror commented on finance-api/internal/store/sqlc.yaml
> +    rule: query.params.size() > 14
It says "seven" but the rule is 14

2024-07-04 12:44 UTC, denialanderror commented on finance-api/internal/store/sqlc.yaml
> +    rule: postgresql.explain.plan.total_cost > 50.0
Is there a reasoning for choosing 50?

2024-07-09 08:06 UTC, denialanderror approved these changes

2024-07-09 09:33 UTC, merged